# this file intentionally misses the prefix
# lines below are padding so that we don't reject the file for being too short;
# in this test, we want to ensure that the lack of prefix is reported

# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
# padding
